### PR TITLE
Implementation of Clean Architecture

### PR DESCRIPTION
**Pull request by kurtxue**
…rchitecture and solid principle.

### CODE REVIEW

**Review by kurtxue — COMMENTED** [review]
very clean architecture

**Comment by Heluhan** [comment]
Good job.

**Review by AlvinXV5 — APPROVED** [review]
The layers are really clear now, great work! Clean architecture is applied and now we can work on connecting these to our frontend codes.

**Comment by Ekconick** [comment]
A very important pull. Making the whole architecture clean and clear. Clean architecture is applied to all the usecase and usecase, and the whole program is connected.The clean architecture of this project is truly impressive. It is clear that a lot of thought and effort went into the design. The code is well organized and easy to read, making it easy to maintain. The modular approach allows for scalability and adaptability. This architecture is an excellent example of well-crafted code.

**Comment by kurtxue** [comment]
Completely redesign the structure of the code, and make the layers of the game clear. By implementing clean architecture, I divided the use cases into login, useCard, throwCard, endTurn, playerjoin, gameboard and globalstatus, based on the user input and application output. I use controller and presenter to separate input and output. Also, I use the input boundary and output boundary to decouple interface adapters and usecase, and use usecase updatable interface to decouple ui and presenter. Moreover, I use response model and request model to define input and output for usecase, making the data communication more clear and structured.

This allows for better management of player information and a more organized flow of the game. Make our game easy to improve or add more features in future iterations.

**Comment by kurtxue** [comment]
Completely redesign the structure of the code, and make the layers of the game clear. By implementing clean architecture, I divided the use cases into login, useCard, throwCard, endTurn, playerjoin, gameboard and globalstatus, based on the user input and application output. I use controller and presenter to separate input and output. Also, I use the input boundary and output boundary to decouple interface adapters and usecase, and use usecase updatable interface to decouple ui and presenter. Moreover, I use response model and request model to define input and output for usecase, making the data communication more clear and structured.

This allows for better management of player information and a more organized flow of the game. Make our game easy to improve or add more features in future iterations.

**Pull request merged**
